LOG_LEVEL: 10
LOG_FORMAT: "%(asctime)-15s | %(name)-10s | %(levelname)-8s | %(message)s"

FAN_PIN: PC5

SLEEP_DURATION_SEC: 10

TIMEZONE: Europe/Moscow

SCHEDULE:
  BASE_POLICY:
    THRESHOLD_ENABLE: 40
    THRESHOLD_DISABLE: 30
